name: ai_panditji
description: "AI-powered Astrology and Horoscope App - एस्ट्रोलॉजी और होरोस्कॉप ऐप"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  provider: ^6.1.1
  google_generative_ai: ^0.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.1
  gradient_borders: ^1.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  font_awesome_flutter: 10.6.0 # Lock the version

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
